// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.21.12
// source: coreum-protos/customparams/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { StakingParams } from "./params";

export const protobufPackage = "coreum.customparams.v1";

/** QueryStakingParamsRequest defines the request type for querying x/customparams staking parameters. */
export interface QueryStakingParamsRequest {
}

/** QueryStakingParamsResponse defines the response type for querying x/customparams staking parameters. */
export interface QueryStakingParamsResponse {
  params: StakingParams | undefined;
}

function createBaseQueryStakingParamsRequest(): QueryStakingParamsRequest {
  return {};
}

export const QueryStakingParamsRequest: MessageFns<QueryStakingParamsRequest> = {
  encode(_: QueryStakingParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryStakingParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryStakingParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryStakingParamsRequest {
    return {};
  },

  toJSON(_: QueryStakingParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryStakingParamsRequest>, I>>(base?: I): QueryStakingParamsRequest {
    return QueryStakingParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryStakingParamsRequest>, I>>(_: I): QueryStakingParamsRequest {
    const message = createBaseQueryStakingParamsRequest();
    return message;
  },
};

function createBaseQueryStakingParamsResponse(): QueryStakingParamsResponse {
  return { params: undefined };
}

export const QueryStakingParamsResponse: MessageFns<QueryStakingParamsResponse> = {
  encode(message: QueryStakingParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      StakingParams.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryStakingParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryStakingParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = StakingParams.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryStakingParamsResponse {
    return { params: isSet(object.params) ? StakingParams.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryStakingParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = StakingParams.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryStakingParamsResponse>, I>>(base?: I): QueryStakingParamsResponse {
    return QueryStakingParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryStakingParamsResponse>, I>>(object: I): QueryStakingParamsResponse {
    const message = createBaseQueryStakingParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? StakingParams.fromPartial(object.params)
      : undefined;
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** StakingParams queries the staking parameters of the module. */
  StakingParams(request: QueryStakingParamsRequest): Promise<QueryStakingParamsResponse>;
}

export const QueryServiceName = "coreum.customparams.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.StakingParams = this.StakingParams.bind(this);
  }
  StakingParams(request: QueryStakingParamsRequest): Promise<QueryStakingParamsResponse> {
    const data = QueryStakingParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "StakingParams", data);
    return promise.then((data) => QueryStakingParamsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
