// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.21.12
// source: coreum-protos/ft/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "cosmjs-types/binary";
import { Coin } from "cosmjs-types/cosmos/base/v1beta1/coin";
import { Duration } from "cosmjs-types/google/protobuf/duration";
import { Timestamp } from "cosmjs-types/google/protobuf/timestamp";

export const protobufPackage = "coreum.asset.ft.v1";

/** Params store gov manageable parameters. */
export interface Params {
  /** issue_fee is the fee burnt each time new token is issued. */
  issueFee: Coin | undefined;
  /** token_upgrade_decision_timeout defines the end of the decision period for upgrading the token. */
  tokenUpgradeDecisionTimeout: Date | undefined;
  /** token_upgrade_grace_period the period after which the token upgrade is executed effectively. */
  tokenUpgradeGracePeriod: Duration | undefined;
}

function createBaseParams(): Params {
  return {
    issueFee: undefined,
    tokenUpgradeDecisionTimeout: undefined,
    tokenUpgradeGracePeriod: undefined,
  };
}

export const Params: MessageFns<Params> = {
  encode(
    message: Params,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.issueFee !== undefined) {
      Coin.encode(message.issueFee, writer.uint32(10).fork()).ldelim();
    }
    if (message.tokenUpgradeDecisionTimeout !== undefined) {
      Timestamp.encode(
        toTimestamp(message.tokenUpgradeDecisionTimeout),
        writer.uint32(18).fork()
      ).ldelim();
    }
    if (message.tokenUpgradeGracePeriod !== undefined) {
      Duration.encode(
        message.tokenUpgradeGracePeriod,
        writer.uint32(26).fork()
      ).ldelim();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.issueFee = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tokenUpgradeDecisionTimeout = fromTimestamp(
            Timestamp.decode(reader, reader.uint32())
          );
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tokenUpgradeGracePeriod = Duration.decode(
            reader,
            reader.uint32()
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      issueFee: isSet(object.issueFee)
        ? Coin.fromJSON(object.issueFee)
        : undefined,
      tokenUpgradeDecisionTimeout: isSet(object.tokenUpgradeDecisionTimeout)
        ? fromJsonTimestamp(object.tokenUpgradeDecisionTimeout)
        : undefined,
      tokenUpgradeGracePeriod: isSet(object.tokenUpgradeGracePeriod)
        ? Duration.fromJSON(object.tokenUpgradeGracePeriod)
        : undefined,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.issueFee !== undefined) {
      obj.issueFee = Coin.toJSON(message.issueFee);
    }
    if (message.tokenUpgradeDecisionTimeout !== undefined) {
      obj.tokenUpgradeDecisionTimeout =
        message.tokenUpgradeDecisionTimeout.toISOString();
    }
    if (message.tokenUpgradeGracePeriod !== undefined) {
      obj.tokenUpgradeGracePeriod = Duration.toJSON(
        message.tokenUpgradeGracePeriod
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.issueFee =
      object.issueFee !== undefined && object.issueFee !== null
        ? Coin.fromPartial(object.issueFee)
        : undefined;
    message.tokenUpgradeDecisionTimeout =
      object.tokenUpgradeDecisionTimeout ?? undefined;
    message.tokenUpgradeGracePeriod =
      object.tokenUpgradeGracePeriod !== undefined &&
      object.tokenUpgradeGracePeriod !== null
        ? Duration.fromPartial(object.tokenUpgradeGracePeriod)
        : undefined;
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
  ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds: BigInt(seconds), nanos };
}

function fromTimestamp(t: Timestamp): Date {
  const seconds = BigInt(t.seconds || 0);
  const nanos = BigInt(t.nanos || 0);

  const millis = seconds * BigInt(1_000) + nanos / BigInt(1_000_000);
  return new Date(Number(millis)); // Convert bigint to number
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
